<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>IronOCR_Demos</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IronOcr" Version="2025.9.7" />
    <PackageReference Include="IronPdf" Version="2025.9.4" />
    <PackageReference Include="IronOcr.Languages.Spanish" Version="2025.9.4" />
    <PackageReference Include="IronOcr.Languages.ChineseSimplified" Version="2025.9.4" />
    <PackageReference Include="IronOcr.Languages.Russian" Version="2025.9.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="Demos\LanguagesGuide\Examples\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Demos\LanguagesGuide\ExpectedText\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
